"""
parking_detector.py — Run detection on your video
──────────────────────────────────────────────────
Uses YOLOv8 trained on VisDrone dataset for top-view vehicle detection.

Usage:
  python parking_detector.py
"""

import cv2
import json
import sys
import numpy as np
from pathlib import Path
from ultralytics import YOLO
import requests


# ─────────────────────────────────────────────
# ADJUST THIS: path to your video file
VIDEO_PATH = "../parking.mp4"

# ADJUST THIS: path to the spots file generated by spot_picker.py
SPOTS_PATH = "parking_spots.json"

# ADJUST THIS: how confident YOLO must be to count a detection (0.0 to 1.0)
CONFIDENCE = 0.4

# ADJUST THIS: how much a car must overlap a spot to call it occupied (0.0 to 1.0)
IOU_THRESHOLD = 0.35

# ADJUST THIS: process every Nth frame (1 = every frame, 2 = every other frame)
FRAME_SKIP = 1

# ADJUST THIS: address of the FastAPI backend
# If running on the same machine, leave this as is
BACKEND_URL = "http://127.0.0.1:8000/update"
# ─────────────────────────────────────────────

# Standard COCO class IDs used by the default YOLOv8 model
VEHICLE_CLASSES = {2: "car", 3: "motorcycle", 5: "bus", 7: "truck"}

# ── Colors (BGR) ─────────────────────────────────────────────────────────────
COLOR_FREE     = (50, 220, 100)
COLOR_OCCUPIED = (50,  70, 220)
COLOR_VEHICLE  = (50, 220, 255)
COLOR_TEXT     = (255, 255, 255)

ALPHA = 0.40
FONT  = cv2.FONT_HERSHEY_SIMPLEX


# ── IoU calculation ──────────────────────────────────────────────────────────

def rect_poly_iou(box: tuple, poly_pts: np.ndarray) -> float:
    x1, y1, x2, y2 = (int(v) for v in box)

    px1 = int(poly_pts[:, 0].min())
    py1 = int(poly_pts[:, 1].min())
    px2 = int(poly_pts[:, 0].max())
    py2 = int(poly_pts[:, 1].max())

    cx1 = min(x1, px1);  cy1 = min(y1, py1)
    cx2 = max(x2, px2);  cy2 = max(y2, py2)
    W = cx2 - cx1 + 1;   H = cy2 - cy1 + 1
    if W <= 0 or H <= 0:
        return 0.0

    box_mask = np.zeros((H, W), dtype=np.uint8)
    box_mask[max(y1 - cy1, 0):y2 - cy1, max(x1 - cx1, 0):x2 - cx1] = 1

    poly_mask = np.zeros((H, W), dtype=np.uint8)
    shifted   = poly_pts - np.array([cx1, cy1])
    cv2.fillPoly(poly_mask, [shifted.astype(np.int32)], 1)

    intersection = np.logical_and(box_mask, poly_mask).sum()
    union        = np.logical_or(box_mask,  poly_mask).sum()
    return float(intersection) / float(union) if union > 0 else 0.0


# ── Detector ─────────────────────────────────────────────────────────────────

class ParkingDetector:

    def __init__(self):
        print("[INFO] Downloading VisDrone model …")
        from huggingface_hub import hf_hub_download
        model_path = hf_hub_download(
            repo_id="keremberke/yolov8n-visdrone",
            filename="best.pt"
        )
        self.model = YOLO(model_path)

        with open(SPOTS_PATH) as f:
            raw = json.load(f)
        self.spots = [np.array(pts, dtype=np.int32) for pts in raw]
        print(f"[INFO] {len(self.spots)} parking spots loaded from {SPOTS_PATH}")

    def detect_vehicles(self, frame):
        results = self.model(frame, conf=CONFIDENCE, verbose=False)[0]

        # ── DEBUG: print every detection to the terminal ──────────────────────
        # This shows what YOLO sees before any filtering.
        # Once detection is working, you can delete these 3 lines.
        for *xyxy, conf, cls in results.boxes.data.tolist():
            print(f"  [DEBUG] class={int(cls)}  conf={conf:.2f}  label={results.names[int(cls)]}")
        # ─────────────────────────────────────────────────────────────────────

        boxes = []
        for *xyxy, conf, cls in results.boxes.data.tolist():
            if int(cls) in VEHICLE_CLASSES:
                boxes.append((xyxy[0], xyxy[1], xyxy[2], xyxy[3], conf, int(cls)))
        return boxes

    def classify_spots(self, vehicle_boxes):
        occupied = []
        for poly in self.spots:
            is_occupied = any(
                rect_poly_iou((x1, y1, x2, y2), poly) >= IOU_THRESHOLD
                for (x1, y1, x2, y2, *_) in vehicle_boxes
            )
            occupied.append(is_occupied)
        return occupied

    def annotate(self, frame, vehicle_boxes, occupied):
        overlay = frame.copy()

        for poly, occ in zip(self.spots, occupied):
            color = COLOR_OCCUPIED if occ else COLOR_FREE
            cv2.fillPoly(overlay, [poly], color)
            cv2.polylines(overlay, [poly], True, color, 2)

        out = cv2.addWeighted(overlay, ALPHA, frame, 1 - ALPHA, 0)

        for poly, occ in zip(self.spots, occupied):
            cx = int(poly[:, 0].mean())
            cy = int(poly[:, 1].mean())
            label = "OCC" if occ else "FREE"
            color = COLOR_OCCUPIED if occ else COLOR_FREE
            cv2.putText(out, label, (cx - 20, cy + 6), FONT, 0.5, (0, 0, 0), 3, cv2.LINE_AA)
            cv2.putText(out, label, (cx - 20, cy + 6), FONT, 0.5, color,      1, cv2.LINE_AA)

        for (x1, y1, x2, y2, conf, cls) in vehicle_boxes:
            cv2.rectangle(out, (int(x1), int(y1)), (int(x2), int(y2)), COLOR_VEHICLE, 2)
            cv2.putText(out, f"{VEHICLE_CLASSES[cls]} {conf:.0%}",
                        (int(x1), int(y1) - 6), FONT, 0.45, COLOR_VEHICLE, 1, cv2.LINE_AA)

        # HUD
        n_free = occupied.count(False)
        n_occ  = occupied.count(True)
        hx, hy, hw, hh = 10, 10, 230, 80
        roi = out[hy:hy + hh, hx:hx + hw].copy()
        cv2.rectangle(out, (hx, hy), (hx + hw, hy + hh), (20, 20, 20), -1)
        out[hy:hy + hh, hx:hx + hw] = cv2.addWeighted(
            out[hy:hy + hh, hx:hx + hw], 0.4, roi, 0.6, 0)

        for j, (text, color) in enumerate([
            (f"Total spots : {len(occupied)}", COLOR_TEXT),
            (f"Free        : {n_free}",        COLOR_FREE),
            (f"Occupied    : {n_occ}",          COLOR_OCCUPIED),
        ]):
            cv2.putText(out, text, (hx + 10, hy + 22 + j * 22),
                        FONT, 0.55, color, 1, cv2.LINE_AA)

        return out


# ── Send data to backend ─────────────────────────────────────────────────────

def send_to_backend(occupied: list):
    """
    Sends the current spot statuses to the FastAPI backend via HTTP POST.

    Why HTTP POST and not WebSocket here?
      The detector is a sender — it pushes data and moves on.
      WebSocket is for the mobile app which needs to stay connected
      and receive updates passively. HTTP POST is simpler and correct
      for a one-way push from a script.

    If the backend is not running, we just print a warning and continue —
    the detector keeps working even without the backend.
    """
    try:
        # Convert booleans to a JSON-serializable list
        # True = occupied, False = free
        requests.post(BACKEND_URL, json={"spots": occupied}, timeout=1)
    except requests.exceptions.ConnectionError:
        print("[WARN] Backend not reachable. Is main.py running?")
    except requests.exceptions.Timeout:
        print("[WARN] Backend did not respond in time.")


# ── Main loop ────────────────────────────────────────────────────────────────

def main():
    if not Path(VIDEO_PATH).exists():
        print(f"[ERROR] Video not found: {VIDEO_PATH}")
        sys.exit(1)
    if not Path(SPOTS_PATH).exists():
        print(f"[ERROR] Spots file not found: {SPOTS_PATH}")
        print("        Run spot_picker.py first.")
        sys.exit(1)

    detector = ParkingDetector()

    cap    = cv2.VideoCapture(VIDEO_PATH)
    fps    = cap.get(cv2.CAP_PROP_FPS) or 25
    width  = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
    height = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
    print(f"[INFO] Video: {width}×{height} @ {fps:.1f} fps")
    print("[INFO] Running … press Q to stop.")

    frame_idx = 0

    while True:
        ret, frame = cap.read()
        if not ret:
            cap.set(cv2.CAP_PROP_POS_FRAMES, 0)
            continue

        frame_idx += 1
        if frame_idx % FRAME_SKIP != 0:
            continue

        boxes     = detector.detect_vehicles(frame)
        occupied  = detector.classify_spots(boxes)
        annotated = detector.annotate(frame, boxes, occupied)

        # Send current spot statuses to the backend
        send_to_backend(occupied)

        disp = annotated
        if width > 1280:
            disp = cv2.resize(annotated, (1280, int(height * 1280 / width)))

        cv2.imshow("Parking Detector  [Q to quit]", disp)
        if cv2.waitKey(1) & 0xFF == ord("q"):
            break

    cap.release()
    cv2.destroyAllWindows()
    print("[DONE]")


